# Dependencies
markdown:         redcarpet
highlighter:      pygments

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# Permalinks
permalink:        pretty

# Setup
title:            Paco G&oacute;mez
tagline:          'blog'
description:      'Paco G&oacute;mez blog.'
url:              http://blog.pacogomez.com
baseurl:          '/'
paginate:         5

author:
  name:           'Paco G&oacute;mez'
  url:            https://pacogomez.com

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
